language: node_js
node_js:
  - "0.10"
  - "0.8"
services:
  - mongodb
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg
  - sudo apt-get install libavahi-compat-libdnssd-dev
  - sudo apt-get build-dep libavahi-compat-libdnssd-dev
